<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['id' => 1, 'name' => 'Afghanistan', 'short_code' => 'AFG'],
            ['id' => 2, 'name' => 'Albania', 'short_code' => 'ALB'],
            ['id' => 3, 'name' => 'Algeria', 'short_code' => 'DZA'],
            ['id' => 4, 'name' => 'American Samoa', 'short_code' => 'ASM'],
            ['id' => 5, 'name' => 'Andorra', 'short_code' => 'AND'],
            ['id' => 6, 'name' => 'Angola', 'short_code' => 'AGO'],
            ['id' => 7, 'name' => 'Anguilla', 'short_code' => 'AIA'],
            ['id' => 8, 'name' => 'Antarctica', 'short_code' => 'ATA'],
            ['id' => 9, 'name' => 'Antigua and Barbuda', 'short_code' => 'ATG'],
            ['id' => 10, 'name' => 'Argentina', 'short_code' => 'ARG'],
            ['id' => 11, 'name' => 'Armenia', 'short_code' => 'ARM'],
            ['id' => 12, 'name' => 'Aruba', 'short_code' => 'ABW'],
            ['id' => 13, 'name' => 'Australia', 'short_code' => 'AUS'],
            ['id' => 14, 'name' => 'Austria', 'short_code' => 'AUT'],
            ['id' => 15, 'name' => 'Azerbaijan', 'short_code' => 'AZE'],
            ['id' => 16, 'name' => 'Bahamas', 'short_code' => 'BHS'],
            ['id' => 17, 'name' => 'Bahrain', 'short_code' => 'BHR'],
            ['id' => 18, 'name' => 'Bangladesh', 'short_code' => 'BGD'],
            ['id' => 19, 'name' => 'Barbados', 'short_code' => 'BRB'],
            ['id' => 20, 'name' => 'Belarus', 'short_code' => 'BLR'],
            ['id' => 21, 'name' => 'Belgium', 'short_code' => 'BEL'],
            ['id' => 22, 'name' => 'Belize', 'short_code' => 'BLZ'],
            ['id' => 23, 'name' => 'Benin', 'short_code' => 'BEN'],
            ['id' => 24, 'name' => 'Bermuda', 'short_code' => 'BMU'],
            ['id' => 25, 'name' => 'Bhutan', 'short_code' => 'BTN'],
            ['id' => 26, 'name' => 'Bolivia', 'short_code' => 'BOL'],
            ['id' => 27, 'name' => 'Bosnia and Herzegovina', 'short_code' => 'BIH'],
            ['id' => 28, 'name' => 'Botswana', 'short_code' => 'BWA'],
            ['id' => 29, 'name' => 'Brazil', 'short_code' => 'BRA'],
            ['id' => 30, 'name' => 'British Indian Ocean Territory', 'short_code' => 'IOT'],
            ['id' => 31, 'name' => 'British Virgin Islands', 'short_code' => 'VGB'],
            ['id' => 32, 'name' => 'Brunei', 'short_code' => 'BRN'],
            ['id' => 33, 'name' => 'Bulgaria', 'short_code' => 'BGR'],
            ['id' => 34, 'name' => 'Burkina Faso', 'short_code' => 'BFA'],
            ['id' => 35, 'name' => 'Burundi', 'short_code' => 'BDI'],
            ['id' => 36, 'name' => 'Cambodia', 'short_code' => 'KHM'],
            ['id' => 37, 'name' => 'Cameroon', 'short_code' => 'CMR'],
            ['id' => 38, 'name' => 'Canada', 'short_code' => 'CAN'],
            ['id' => 39, 'name' => 'Cape Verde', 'short_code' => 'CPV'],
            ['id' => 40, 'name' => 'Cayman Islands', 'short_code' => 'CYM'],
            ['id' => 41, 'name' => 'Central African Republic', 'short_code' => 'CAF'],
            ['id' => 42, 'name' => 'Chad', 'short_code' => 'TCD'],
            ['id' => 43, 'name' => 'Chile', 'short_code' => 'CHL'],
            ['id' => 44, 'name' => 'China', 'short_code' => 'CHN'],
            ['id' => 45, 'name' => 'Christmas Island', 'short_code' => 'CXR'],
            ['id' => 46, 'name' => 'Cocos Islands', 'short_code' => 'CCK'],
            ['id' => 47, 'name' => 'Colombia', 'short_code' => 'COL'],
            ['id' => 48, 'name' => 'Comoros', 'short_code' => 'COM'],
            ['id' => 49, 'name' => 'Cook Islands', 'short_code' => 'COK'],
            ['id' => 50, 'name' => 'Costa Rica', 'short_code' => 'CRI'],
            ['id' => 51, 'name' => 'Croatia', 'short_code' => 'HRV'],
            ['id' => 52, 'name' => 'Cuba', 'short_code' => 'CUB'],
            ['id' => 53, 'name' => 'Curacao', 'short_code' => 'CUW'],
            ['id' => 54, 'name' => 'Cyprus', 'short_code' => 'CYP'],
            ['id' => 55, 'name' => 'Czech Republic', 'short_code' => 'CZE'],
            ['id' => 56, 'name' => 'Democratic Republic of the Congo', 'short_code' => 'COD'],
            ['id' => 57, 'name' => 'Denmark', 'short_code' => 'DNK'],
            ['id' => 58, 'name' => 'Djibouti', 'short_code' => 'DJI'],
            ['id' => 59, 'name' => 'Dominica', 'short_code' => 'DMA'],
            ['id' => 60, 'name' => 'Dominican Republic', 'short_code' => 'DOM'],
            ['id' => 61, 'name' => 'East Timor', 'short_code' => 'TLS'],
            ['id' => 62, 'name' => 'Ecuador', 'short_code' => 'ECU'],
            ['id' => 63, 'name' => 'Egypt', 'short_code' => 'EGY'],
            ['id' => 64, 'name' => 'El Salvador', 'short_code' => 'SLV'],
            ['id' => 65, 'name' => 'Equatorial Guinea', 'short_code' => 'GNQ'],
            ['id' => 66, 'name' => 'Eritrea', 'short_code' => 'ERI'],
            ['id' => 67, 'name' => 'Estonia', 'short_code' => 'EST'],
            ['id' => 68, 'name' => 'Ethiopia', 'short_code' => 'ETH'],
            ['id' => 69, 'name' => 'Falkland Islands', 'short_code' => 'FLK'],
            ['id' => 70, 'name' => 'Faroe Islands', 'short_code' => 'FRO'],
            ['id' => 71, 'name' => 'Fiji', 'short_code' => 'FJI'],
            ['id' => 72, 'name' => 'Finland', 'short_code' => 'FIN'],
            ['id' => 73, 'name' => 'France', 'short_code' => 'FRA'],
            ['id' => 74, 'name' => 'French Polynesia', 'short_code' => 'PYF'],
            ['id' => 75, 'name' => 'Gabon', 'short_code' => 'GAB'],
            ['id' => 76, 'name' => 'Gambia', 'short_code' => 'GMB'],
            ['id' => 77, 'name' => 'Georgia', 'short_code' => 'GEO'],
            ['id' => 78, 'name' => 'Germany', 'short_code' => 'DEU'],
            ['id' => 79, 'name' => 'Ghana', 'short_code' => 'GHA'],
            ['id' => 80, 'name' => 'Gibraltar', 'short_code' => 'GIB'],
            ['id' => 81, 'name' => 'Greece', 'short_code' => 'GRC'],
            ['id' => 82, 'name' => 'Greenland', 'short_code' => 'GRL'],
            ['id' => 83, 'name' => 'Grenada', 'short_code' => 'GRD'],
            ['id' => 84, 'name' => 'Guam', 'short_code' => 'GUM'],
            ['id' => 85, 'name' => 'Guatemala', 'short_code' => 'GTM'],
            ['id' => 86, 'name' => 'Guernsey', 'short_code' => 'GGY'],
            ['id' => 87, 'name' => 'Guinea', 'short_code' => 'GIN'],
            ['id' => 88, 'name' => 'Guinea-Bissau', 'short_code' => 'GNB'],
            ['id' => 89, 'name' => 'Guyana', 'short_code' => 'GUY'],
            ['id' => 90, 'name' => 'Haiti', 'short_code' => 'HTI'],
            ['id' => 91, 'name' => 'Honduras', 'short_code' => 'HND'],
            ['id' => 92, 'name' => 'Hong Kong', 'short_code' => 'HKG'],
            ['id' => 93, 'name' => 'Hungary', 'short_code' => 'HUN'],
            ['id' => 94, 'name' => 'Iceland', 'short_code' => 'ISL'],
            ['id' => 95, 'name' => 'India', 'short_code' => 'IND'],
            ['id' => 96, 'name' => 'Indonesia', 'short_code' => 'IDN'],
            ['id' => 97, 'name' => 'Iran', 'short_code' => 'IRN'],
            ['id' => 98, 'name' => 'Iraq', 'short_code' => 'IRQ'],
            ['id' => 99, 'name' => 'Ireland', 'short_code' => 'IRL'],
            ['id' => 100, 'name' => 'Isle of Man', 'short_code' => 'IMN'],
            ['id' => 101, 'name' => 'Israel', 'short_code' => 'ISR'],
            ['id' => 102, 'name' => 'Italy', 'short_code' => 'ITA'],
            ['id' => 103, 'name' => 'Ivory Coast', 'short_code' => 'CIV'],
            ['id' => 104, 'name' => 'Jamaica', 'short_code' => 'JAM'],
            ['id' => 105, 'name' => 'Japan', 'short_code' => 'JPN'],
            ['id' => 106, 'name' => 'Jersey', 'short_code' => 'JEY'],
            ['id' => 107, 'name' => 'Jordan', 'short_code' => 'JOR'],
            ['id' => 108, 'name' => 'Kazakhstan', 'short_code' => 'KAZ'],
            ['id' => 109, 'name' => 'Kenya', 'short_code' => 'KEN'],
            ['id' => 110, 'name' => 'Kiribati', 'short_code' => 'KIR'],
            ['id' => 111, 'name' => 'Kosovo', 'short_code' => 'XKX'],
            ['id' => 112, 'name' => 'Kuwait', 'short_code' => 'KWT'],
            ['id' => 113, 'name' => 'Kyrgyzstan', 'short_code' => 'KGZ'],
            ['id' => 114, 'name' => 'Laos', 'short_code' => 'LAO'],
            ['id' => 115, 'name' => 'Latvia', 'short_code' => 'LVA'],
            ['id' => 116, 'name' => 'Lebanon', 'short_code' => 'LBN'],
            ['id' => 117, 'name' => 'Lesotho', 'short_code' => 'LSO'],
            ['id' => 118, 'name' => 'Liberia', 'short_code' => 'LBR'],
            ['id' => 119, 'name' => 'Libya', 'short_code' => 'LBY'],
            ['id' => 120, 'name' => 'Liechtenstein', 'short_code' => 'LIE'],
            ['id' => 121, 'name' => 'Lithuania', 'short_code' => 'LTU'],
            ['id' => 122, 'name' => 'Luxembourg', 'short_code' => 'LUX'],
            ['id' => 123, 'name' => 'Macau', 'short_code' => 'MAC'],
            ['id' => 124, 'name' => 'North Macedonia', 'short_code' => 'MKD'],
            ['id' => 125, 'name' => 'Madagascar', 'short_code' => 'MDG'],
            ['id' => 126, 'name' => 'Malawi', 'short_code' => 'MWI'],
            ['id' => 127, 'name' => 'Malaysia', 'short_code' => 'MYS'],
            ['id' => 128, 'name' => 'Maldives', 'short_code' => 'MDV'],
            ['id' => 129, 'name' => 'Mali', 'short_code' => 'MLI'],
            ['id' => 130, 'name' => 'Malta', 'short_code' => 'MLT'],
            ['id' => 131, 'name' => 'Marshall Islands', 'short_code' => 'MHL'],
            ['id' => 132, 'name' => 'Mauritania', 'short_code' => 'MRT'],
            ['id' => 133, 'name' => 'Mauritius', 'short_code' => 'MUS'],
            ['id' => 134, 'name' => 'Mayotte', 'short_code' => 'MYT'],
            ['id' => 135, 'name' => 'Mexico', 'short_code' => 'MEX'],
            ['id' => 136, 'name' => 'Micronesia', 'short_code' => 'FSM'],
            ['id' => 137, 'name' => 'Moldova', 'short_code' => 'MDA'],
            ['id' => 138, 'name' => 'Monaco', 'short_code' => 'MCO'],
            ['id' => 139, 'name' => 'Mongolia', 'short_code' => 'MNG'],
            ['id' => 140, 'name' => 'Montenegro', 'short_code' => 'MNE'],
            ['id' => 141, 'name' => 'Montserrat', 'short_code' => 'MSR'],
            ['id' => 142, 'name' => 'Morocco', 'short_code' => 'MAR'],
            ['id' => 143, 'name' => 'Mozambique', 'short_code' => 'MOZ'],
            ['id' => 144, 'name' => 'Myanmar', 'short_code' => 'MMR'],
            ['id' => 145, 'name' => 'Namibia', 'short_code' => 'NAM'],
            ['id' => 146, 'name' => 'Nauru', 'short_code' => 'NRU'],
            ['id' => 147, 'name' => 'Nepal', 'short_code' => 'NPL'],
            ['id' => 148, 'name' => 'Netherlands', 'short_code' => 'NLD'],
            ['id' => 149, 'name' => 'Netherlands Antilles', 'short_code' => 'ANT'],
            ['id' => 150, 'name' => 'New Caledonia', 'short_code' => 'NCL'],
            ['id' => 151, 'name' => 'New Zealand', 'short_code' => 'NZL'],
            ['id' => 152, 'name' => 'Nicaragua', 'short_code' => 'NIC'],
            ['id' => 153, 'name' => 'Niger', 'short_code' => 'NER'],
            ['id' => 154, 'name' => 'Nigeria', 'short_code' => 'NGA'],
            ['id' => 155, 'name' => 'Niue', 'short_code' => 'NIU'],
            ['id' => 156, 'name' => 'North Korea', 'short_code' => 'PRK'],
            ['id' => 157, 'name' => 'Northern Mariana Islands', 'short_code' => 'MNP'],
            ['id' => 158, 'name' => 'Norway', 'short_code' => 'NOR'],
            ['id' => 159, 'name' => 'Oman', 'short_code' => 'OMN'],
            ['id' => 160, 'name' => 'Pakistan', 'short_code' => 'PAK'],
            ['id' => 161, 'name' => 'Palau', 'short_code' => 'PLW'],
            ['id' => 162, 'name' => 'Palestine', 'short_code' => 'PSE'],
            ['id' => 163, 'name' => 'Panama', 'short_code' => 'PAN'],
            ['id' => 164, 'name' => 'Papua New Guinea', 'short_code' => 'PNG'],
            ['id' => 165, 'name' => 'Paraguay', 'short_code' => 'PRY'],
            ['id' => 166, 'name' => 'Peru', 'short_code' => 'PER'],
            ['id' => 167, 'name' => 'Philippines', 'short_code' => 'PHL'],
            ['id' => 168, 'name' => 'Pitcairn', 'short_code' => 'PCN'],
            ['id' => 169, 'name' => 'Poland', 'short_code' => 'POL'],
            ['id' => 170, 'name' => 'Portugal', 'short_code' => 'PRT'],
            ['id' => 171, 'name' => 'Puerto Rico', 'short_code' => 'PRI'],
            ['id' => 172, 'name' => 'Qatar', 'short_code' => 'QAT'],
            ['id' => 173, 'name' => 'Republic of the Congo', 'short_code' => 'COG'],
            ['id' => 174, 'name' => 'Reunion', 'short_code' => 'REU'],
            ['id' => 175, 'name' => 'Romania', 'short_code' => 'ROU'],
            ['id' => 176, 'name' => 'Russia', 'short_code' => 'RUS'],
            ['id' => 177, 'name' => 'Rwanda', 'short_code' => 'RWA'],
            ['id' => 178, 'name' => 'Saint Barthelemy', 'short_code' => 'BLM'],
            ['id' => 179, 'name' => 'Saint Helena', 'short_code' => 'SHN'],
            ['id' => 180, 'name' => 'Saint Kitts and Nevis', 'short_code' => 'KNA'],
            ['id' => 181, 'name' => 'Saint Lucia', 'short_code' => 'LCA'],
            ['id' => 182, 'name' => 'Saint Martin', 'short_code' => 'MAF'],
            ['id' => 183, 'name' => 'Saint Pierre and Miquelon', 'short_code' => 'SPM'],
            ['id' => 184, 'name' => 'Saint Vincent and the Grenadines', 'short_code' => 'VCT'],
            ['id' => 185, 'name' => 'Samoa', 'short_code' => 'WSM'],
            ['id' => 186, 'name' => 'San Marino', 'short_code' => 'SMR'],
            ['id' => 187, 'name' => 'Sao Tome and Principe', 'short_code' => 'STP'],
            ['id' => 188, 'name' => 'Saudi Arabia', 'short_code' => 'SAU'],
            ['id' => 189, 'name' => 'Senegal', 'short_code' => 'SEN'],
            ['id' => 190, 'name' => 'Serbia', 'short_code' => 'SRB'],
            ['id' => 191, 'name' => 'Seychelles', 'short_code' => 'SYC'],
            ['id' => 192, 'name' => 'Sierra Leone', 'short_code' => 'SLE'],
            ['id' => 193, 'name' => 'Singapore', 'short_code' => 'SGP'],
            ['id' => 194, 'name' => 'Sint Maarten', 'short_code' => 'SXM'],
            ['id' => 195, 'name' => 'Slovakia', 'short_code' => 'SVK'],
            ['id' => 196, 'name' => 'Slovenia', 'short_code' => 'SVN'],
            ['id' => 197, 'name' => 'Solomon Islands', 'short_code' => 'SLB'],
            ['id' => 198, 'name' => 'Somalia', 'short_code' => 'SOM'],
            ['id' => 199, 'name' => 'South Africa', 'short_code' => 'ZAF'],
            ['id' => 200, 'name' => 'South Korea', 'short_code' => 'KOR'],
            ['id' => 201, 'name' => 'South Sudan', 'short_code' => 'SSD'],
            ['id' => 202, 'name' => 'Spain', 'short_code' => 'ESP'],
            ['id' => 203, 'name' => 'Sri Lanka', 'short_code' => 'LKA'],
            ['id' => 204, 'name' => 'Sudan', 'short_code' => 'SDN'],
            ['id' => 205, 'name' => 'Suriname', 'short_code' => 'SUR'],
            ['id' => 206, 'name' => 'Svalbard and Jan Mayen', 'short_code' => 'SJM'],
            ['id' => 207, 'name' => 'Swaziland', 'short_code' => 'SWZ'],
            ['id' => 208, 'name' => 'Sweden', 'short_code' => 'SWE'],
            ['id' => 209, 'name' => 'Switzerland', 'short_code' => 'CHE'],
            ['id' => 210, 'name' => 'Syria', 'short_code' => 'SYR'],
            ['id' => 211, 'name' => 'Taiwan', 'short_code' => 'TWN'],
            ['id' => 212, 'name' => 'Tajikistan', 'short_code' => 'TJK'],
            ['id' => 213, 'name' => 'Tanzania', 'short_code' => 'TZA'],
            ['id' => 214, 'name' => 'Thailand', 'short_code' => 'THA'],
            ['id' => 215, 'name' => 'Togo', 'short_code' => 'TGO'],
            ['id' => 216, 'name' => 'Tokelau', 'short_code' => 'TKL'],
            ['id' => 217, 'name' => 'Tonga', 'short_code' => 'TON'],
            ['id' => 218, 'name' => 'Trinidad and Tobago', 'short_code' => 'TTO'],
            ['id' => 219, 'name' => 'Tunisia', 'short_code' => 'TUN'],
            ['id' => 220, 'name' => 'Turkey', 'short_code' => 'TUR'],
            ['id' => 221, 'name' => 'Turkmenistan', 'short_code' => 'TKM'],
            ['id' => 222, 'name' => 'Turks and Caicos Islands', 'short_code' => 'TCA'],
            ['id' => 223, 'name' => 'Tuvalu', 'short_code' => 'TUV'],
            ['id' => 224, 'name' => 'U.S. Virgin Islands', 'short_code' => 'VIR'],
            ['id' => 225, 'name' => 'Uganda', 'short_code' => 'UGA'],
            ['id' => 226, 'name' => 'Ukraine', 'short_code' => 'UKR'],
            ['id' => 227, 'name' => 'United Arab Emirates', 'short_code' => 'ARE'],
            ['id' => 228, 'name' => 'United Kingdom', 'short_code' => 'GBR'],
            ['id' => 229, 'name' => 'United States', 'short_code' => 'USA'],
            ['id' => 230, 'name' => 'Uruguay', 'short_code' => 'URY'],
            ['id' => 231, 'name' => 'Uzbekistan', 'short_code' => 'UZB'],
            ['id' => 232, 'name' => 'Vanuatu', 'short_code' => 'VUT'],
            ['id' => 233, 'name' => 'Vatican', 'short_code' => 'VAT'],
            ['id' => 234, 'name' => 'Venezuela', 'short_code' => 'VEN'],
            ['id' => 235, 'name' => 'Vietnam', 'short_code' => 'VNM'],
            ['id' => 236, 'name' => 'Wallis and Futuna', 'short_code' => 'WLF'],
            ['id' => 237, 'name' => 'Western Sahara', 'short_code' => 'ESH'],
            ['id' => 238, 'name' => 'Yemen', 'short_code' => 'YEM'],
            ['id' => 239, 'name' => 'Zambia', 'short_code' => 'ZMB'],
            ['id' => 240, 'name' => 'Zimbabwe', 'short_code' => 'ZWE'],
        ];


        $chunks = array_chunk($countries, 50);

        foreach ($chunks as $chunk) {
            Country::insert($chunk);
        }

    }
}
