---
deployment:
  tasks:
    - echo "Setting Deployment Folder" > deployment.txt
    - export DEPLOYPATH=/home/stubbie/public_html/
    - echo "Copying To Deployment Folder" >> deployment.txt
    - /bin/cp -R . $DEPLOYPATH
    - echo "Copy Complete" >> deployment.txt
    - echo "Current Folder:" >> deployment.txt
    - pwd >> deployment.txt
    - echo "Changing to Deployment Folder" >> deployment.txt
    - cd $DEPLOYPATH
    - pwd >> deployment.txt
