deployment:
  tasks:
    - export DEPLOYPATH=/home/stubbie/public_html/
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH
    - pwd
    - php artisan install
#    - php artisan migrate
#    - npm install
#    - npm run build
